plugins {
    id 'com.android.application'
}

android {
    compileSdk 37

    defaultConfig {
        applicationId "com.bit747.clipboardfilter"
        minSdk 28
        targetSdk 35
        versionCode 20
        versionName "2.0"
    }

    buildTypes {
        release {
            // 保持不混淆；一旦开启 minifyEnabled，proguard-rules.pro 中的 libxposed 三件套必须生效
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            merges += "META-INF/xposed/*"
            excludes += "**"
        }
    }

    namespace 'com.bit747.clipboardfilter'
}

dependencies {
    compileOnly 'io.github.libxposed:api:102.0.0'
    implementation 'io.github.libxposed:service:102.0.0'
}
